### PR TITLE
fix: crash when accessing 'accessible' attribute in non mobile driver…

### LINKED ISSUE #662: An unexpected error occurred with message: Cannot read property 'accessible' of undefined.
Hi,all:

When i use Appium Desktop, i have this problem ：

## The problem

when i click Start Session, it become:

企业微信截图_1634d053-2983-45f8-b12e-5b4607246bcb

企业微信截图_d781c6c1-19f7-4e85-a12b-442d3da2ac67

Log:
kksusu@test-mac~ $ appium -p 4623
[Appium] Welcome to Appium v1.22.3
[Appium] Non-default server args:
[Appium]   port: 4623
[Appium] Appium REST http interface listener started on 0.0.0.0:4623
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getSessions() with args: []
[debug] [GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 304 6 ms - -
[HTTP]
[HTTP] --> GET /wd/hub/sessions
[HTTP] {}
[debug] [GENERIC] Calling AppiumDriver.getSessions() with args: []
[debug] [GENERIC] Responding to client with driver.getSessions() result: []
[HTTP] <-- GET /wd/hub/sessions 304 1 ms - -
[HTTP]
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"mac","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"mac","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[debug] [W3C] Calling AppiumDriver.createSession() with args: [{"platformName":"mac","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"mac","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [BaseDriver] Event 'newSessionRequested' logged at 1668150461901 (15:07:41 GMT+0800 (中国标准时间))
[Appium] Appium v1.22.3 creating new MacDriver (v1.10.2) session
[debug] [BaseDriver] W3C capabilities and MJSONWP desired capabilities were provided
[debug] [BaseDriver] Creating session with W3C capabilities: {
[debug] [BaseDriver]   "alwaysMatch": {
[debug] [BaseDriver]     "platformName": "mac",
[debug] [BaseDriver]     "appium:newCommandTimeout": 3600,
[debug] [BaseDriver]     "appium:connectHardwareKeyboard": true
[debug] [BaseDriver]   },
[debug] [BaseDriver]   "firstMatch": [
[debug] [BaseDriver]     {}
[debug] [BaseDriver]   ]
[debug] [BaseDriver] }
[BaseDriver] The following capabilities were provided, but are not recognized by Appium:
[BaseDriver]   connectHardwareKeyboard
[BaseDriver] Session created with session id: af39f751-b68b-49d5-a6d9-9e7f44a4a6f5
[debug] [MacDriver] The path to AppiumForMac server has not been provided explicitly. Trying to autodetect it
[MacDriver] Autodetected AppiumForMac server's location at '/Applications/AppiumForMac.app'
[MacDriver] Killing any old AppiumForMac
[MacDriver] Successfully cleaned up old Appium4Mac servers
[MacDriver] Spawning AppiumForMac with: /Applications/AppiumForMac.app
[Appium4Mac] [STDERR] 2022-11-11 15:07:42:365 AppiumForMac[98112:103] HTTPServer: Started HTTP server on port 4622
[debug] [WD Proxy] Matched '/session' to command name 'createSession'
[debug] [WD Proxy] Proxying [POST /session] to [POST http://127.0.0.1:4622/wd/hub/session] with body: {"desiredCapabilities":{"platformName":"mac","newCommandTimeout":3600,"connectHardwareKeyboard":true}}
[debug] [WD Proxy] Got response with status 200: {"status":0,"sessionId":"hr5iOmLE","value":{"locationContextEnabled":false,"webStorageEnabled":false,"browserName":"Mac","platform":"Mac","databaseEnabled":false,"version":"10.16","javascriptEnabled":true,"takesScreenshot":true,"nativeEvents":true}}
[WD Proxy] Determined the downstream protocol as 'MJSONWP'
[Appium] New MacDriver session created successfully, session af39f751-b68b-49d5-a6d9-9e7f44a4a6f5 added to master session list
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1668150462569 (15:07:42 GMT+0800 (中国标准时间))
[debug] [W3C (af39f751)] Cached the protocol value 'W3C' for the new session af39f751-b68b-49d5-a6d9-9e7f44a4a6f5
[debug] [W3C (af39f751)] Responding to client with driver.createSession() result: {"capabilities":{"platformName":"mac","newCommandTimeout":3600,"connectHardwareKeyboard":true}}
[HTTP] <-- POST /wd/hub/session 200 672 ms - 156
[HTTP]
[HTTP] --> GET /wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/screenshot
[HTTP] {}
[W3C (af39f751)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/screenshot] to [GET http://127.0.0.1:4622/wd/hub/session/hr5iOmLE/screenshot] with no body
[debug] [WD Proxy] Got response with status 200: {"status":0,"sessionId":"hr5iOmLE","value":"iVBORw0KGgoAAAANSUhEUgAAC0AAAAcICAYAAACv5EAVAAAMPmlDQ1BJQ0MgUHJv\r\nZmlsZQAASImVVwdYU8kWnluSkJDQAqFICb0JItKREkKLVKmCjZAECCXEQFCxI6KC\r\naxcL2NBVEQXXAshaEbuLomLXxQLCyrpYsCtvUkCXfeV7831z57//nPnPmXNn7r0D\r\ngPoprlicjWoAkCPKl8SEBDAnJCUzSV1AFRAAFVgDLS4vT8yKjg4HsAy2fy/vbgFE\r\n1t5wkGn9s/+/Fk2+II8HABINcSo/j5cD8WEA8EqeWJIPAFHGm0/PF8swrEBbAgOE\r\neIkMpytwpQynKvABuU1cDBviFgBUqFyuJB0AtWuQZxbw0qGGWh/ETiK+UASAOhNi\r\n35ycXD7EKRDbQBsxxDJ9j9QfdNL/ppk6pMnlpg9hxVzkRSVQmCfO5s78P9Pxv0tO\r\ntnTQhxWs1AxJaIxszjBvd7Jyw2SYCnGvKDUyCmItiD8I+XJ7iFFKhjQ0XmGPGvLy\r\n2DBngAGxE58bGAaxIcTBouzIcCWfmiYM5kAMVwg6Q5jPiYNYD+IlgrygWKXNNklu\r\njNIXWp8mYbOU/AWuRO5X5uuRNCuepdR/nSHgKPUxtcKMuESIKRBbFAgTIiFWg9gx\r\nLys2TGkztjCDHTloI5HGyOK3gDhGIAoJUOhjBWmS4BilfWlO3uB8sW0ZQk6kEh/M\r\nz4gLVeQHa+Fx5fHDuWDXBCJW/KCOIG9C+OBc+ILAIMXcsW6BKD5WqfNBnB8QoxiL\r\nU8TZ0Up73EyQHSLjzSB2ySuIVY7FE/LhglTo42ni/Og4RZx4YSZ3XLQiHnwlCAds\r\nEAiYQAprKsgFmUDY2tvQC+8UPcGACyQgHQiAg5IZHJEo7xHBaywoBH9CJAB5Q+MC\r\n5L0CUAD5r0Os4uoA0uS9BfIRW...
[WD Proxy] Replacing sessionId hr5iOmLE with af39f751-b68b-49d5-a6d9-9e7f44a4a6f5
[HTTP] <-- GET /wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/screenshot 200 398 ms - 1307991
[HTTP]
[HTTP] --> GET /wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/source
[HTTP] {}
[W3C (af39f751)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/source' to command name 'getPageSource'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/source] to [GET http://127.0.0.1:4622/wd/hub/session/hr5iOmLE/source] with no body
[debug] [WD Proxy] Got response with status 200: {"status":0,"sessionId":"hr5iOmLE","value":"<?xml version=\"1.0\"?>\n"}
[WD Proxy] Replacing sessionId hr5iOmLE with af39f751-b68b-49d5-a6d9-9e7f44a4a6f5
[HTTP] <-- GET /wd/hub/session/af39f751-b68b-49d5-a6d9-9e7f44a4a6f5/source 200 6 ms - 88
[HTTP]

## Environment

Appium Inspector Version： Appium-Inspector-mac-2022.9.1
 I am on Mac
Appium server version: v1.22.3

### PR DESCRIPTION
**Pull request by jlipps**
… (fix #662)

### CODE REVIEW

File: app/renderer/components/Inspector/HighlighterRects.js [hunk 1]
```diff
@@ -83,7 +83,7 @@ export default class HighlighterRects extends Component {
         path: source.path,
         keyCode: null,
         container: false,
-        accessible: source.attributes.accessible
+        accessible: source.attributes ? source.attributes.accessible : null
```
Comment (mykola-mokhnach) [inline app/renderer/components/Inspector/HighlighterRects.js:86]: you could probably use `?.` operator

Comment (jlipps) [reply app/renderer/components/Inspector/HighlighterRects.js:86]: i tried that, the build system the inspector uses doesn't handle it

**Review by mykola-mokhnach — APPROVED** [review]
