### PR TITLE
fix: fix typo so that adding vendor prefixes works correctly (fix #68)

### LINKED ISSUE #68: prefixed with "appium:" are set repeatedly
## Appium or Appium Desktop?

- [x] I have verified that my issue does not occur with Appium and should be investigated as an Appium Desktop issue

## The problem
prefixed with "appium:" are set repeatedly while I click the _**startSession**_ button .
It seems that because of this [PR](https://github.com/appium/appium-inspector/pull/65/files#diff-cc0a8b1e7efd7e5b9ee01a00c256283251315b2c0c18cca08911fef1c01fa0b9R181
).
@jlipps 

https://user-images.githubusercontent.com/46949537/125063592-3e74ba00-e0e2-11eb-9117-4414f9af529c.mov

## Environment

- I am running Appium Desktop version _<insert version here>_.
- I am on (pick one):
    - [x] Mac
    - [ ] Windows
    - [ ] Linux

- branch: main

### PR DESCRIPTION
**Pull request by jlipps**

### CODE REVIEW

**Review by mykola-mokhnach — APPROVED** [review]

File: app/renderer/actions/Session.js [hunk 1]
```diff
@@ -182,7 +182,7 @@ export function removeCapability (index) {
 function addVendorPrefixes (caps, dispatch, getState) {
   const prefixedCaps = caps.map((cap) => {
     // if we don't have a valid unprefixed cap or a cap with an existing prefix, update it
-    if (!VALID_W3C_CAPS.includes(cap.name) && !includes(caps.name, ':')) {
+    if (!VALID_W3C_CAPS.includes(cap.name) && !includes(cap.name, ':')) {
```
Comment (mykola-mokhnach) [inline app/renderer/actions/Session.js:185]: a unit test would be nice

Comment (jlipps) [reply app/renderer/actions/Session.js]: sigh, i suppose you're right :-)
