### PR TITLE
fix: adjust calculation of element highlighter positions

### LINKED ISSUE #1680: bug: Screenshot Panel coordinates are incorrect when session is started in landscape mode or the inspector window is resized
### Is this an issue specifically with Appium Inspector?

- [X] I have verified that my issue does _not_ occur with Appium, and should be investigated as an Appium Inspector issue

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- When the session is started with the **DUT in landscape mode**, after the screenshot is displayed, the **screenshot panel is automatically resized**, causing the coordinates of elements to become inaccurate. The highlights and interaction areas no longer align with their actual positions on the device screen. This misalignment happens immediately after the panel is resized automatically.
- In **portrait mode**, the issue does not occur until the **Appium Inspector window** is manually resized. After resizing, the coordinates in the screenshot panel become incorrect, making UI element inspection and interaction unreliable.
- Using the **Refresh Source & Screenshot** button resolves the issue in both modes. After manually refreshing, the coordinates are corrected and interactions work as expected.

Screenshot 2024-09-13 at 07 03 57

### Expected Behavior

- The screenshot panel should display accurate coordinates for UI elements, regardless of whether the DUT is in portrait or landscape mode. Any window resizing (manual or automatic) should not break the coordinate mapping.
- Whether the screenshot is in portrait or landscape, and regardless of any resizing events, the coordinates and highlighted areas should always match the actual positions on the device screen without needing to manually refresh.

### Operating System

Mac

### Appium Inspector Version

2024.8.2

### Appium Version

2.11.3

### Further Information

_No response_

### PR DESCRIPTION
**Pull request by eglitise**
This PR fixes the issue where element highlighters over the screenshot were sometimes drawn over incorrect coordinates. This commonly happened when starting a session directly into landscape mode, or resizing the Inspector window height (not width). The underlying cause was that the scale ratio for drawing highlighters was using old data.
The overall implementation has also been slightly simplified, and the unnecessary 500ms debounce was removed, so now the highlighter update is subject to the same 50ms debounce used for calculating the screenshot scale - it feels much more responsive.

Fixes #1680.

### CODE REVIEW

File: app/common/renderer/components/Inspector/Inspector.jsx [hunk 1]
```diff
@@ -92,23 +90,16 @@ const Inspector = (props) => {
...
+    // If the screenshot has too much space to the right or bottom, adjust the max width
+    // of its container, so the source tree always fills the remaining space.
+    // This keeps everything looking tight.
+    if (!screenshotContainerEl.current) {
       return;
     }
 
-    const screenshotBox = screenAndSourceEl.current.querySelector('#screenshotContainer');
-    const img = screenAndSourceEl.current.querySelector('#screenshotContainer img#screenshot');
+    const screenshotBox = screenshotContainerEl.current;
```
Comment (mykola-mokhnach) [inline app/common/renderer/components/Inspector/Inspector.jsx:101]: should we use screenshotBox everywhere instead of screenshotContainerEl.current ?

**Review by mykola-mokhnach — APPROVED** [review]

**Review by jlipps — COMMENTED** [review]
amazing, thanks for this
